// Generates eaw-table.ts from Unicode's EastAsianWidth.txt (plan §1c S7).
//
// Usage: node gen-eaw-table.node.ts <EastAsianWidth.txt> > eaw-table.ts
// Source: https://www.unicode.org/Public/<version>/ucd/EastAsianWidth.txt — use the
// version of `node -p process.versions.unicode`, so the table agrees with
// Intl.Segmenter and the regex \p{Emoji*} properties the TUI also uses.

import { readFileSync } from 'node:fs'

const path = process.argv[2]
if (!path) {
  process.stderr.write('usage: node gen-eaw-table.node.ts <EastAsianWidth.txt>\n')
  process.exit(2)
}
const text = readFileSync(path, 'utf8')
const version = /^# EastAsianWidth-(\d+\.\d+\.\d+)\.txt/.exec(text)?.[1]
if (!version) {
  process.stderr.write(`${path}: first line is not "# EastAsianWidth-<version>.txt"\n`)
  process.exit(2)
}

// 2 = W or F (both 2 cells in rule 5), 1 = A. Everything else stays 0 (not in the table).
const cls = new Uint8Array(0x110000)
// The file's header: these unassigned code points default to W even when not listed.
for (const [a, b] of [
  [0x3400, 0x4dbf],
  [0x4e00, 0x9fff],
  [0xf900, 0xfaff],
  [0x20000, 0x2fffd],
  [0x30000, 0x3fffd],
]) cls.fill(2, a!, b! + 1)
for (const line of text.split('\n')) {
  const m = /^([0-9A-F]+)(?:\.\.([0-9A-F]+))?\s*;\s*(\w+)/.exec(line)
  if (!m) continue
  const a = parseInt(m[1]!, 16)
  const b = m[2] ? parseInt(m[2], 16) : a
  cls.fill(m[3] === 'W' || m[3] === 'F' ? 2 : m[3] === 'A' ? 1 : 0, a, b + 1)
}

const ranges = (want: number): number[] => {
  const out: number[] = []
  for (let cp = 0; cp < cls.length; cp++) {
    if (cls[cp] !== want) continue
    const start = cp
    while (cp + 1 < cls.length && cls[cp + 1] === want) cp++
    out.push(start, cp)
  }
  return out
}
const hex = (xs: number[]) => {
  const pairs: string[] = []
  for (let i = 0; i < xs.length; i += 2) pairs.push(`0x${xs[i]!.toString(16)}, 0x${xs[i + 1]!.toString(16)}`)
  return pairs.map(p => `  ${p},`).join('\n')
}

process.stdout.write(`// GENERATED by gen-eaw-table.node.ts from EastAsianWidth-${version}.txt. Do not edit.
// Regenerate: node gen-eaw-table.node.ts EastAsianWidth.txt > eaw-table.ts

export const EAW_UNICODE_VERSION = '${version}'

/** East_Asian_Width W or F: flat [first, last, first, last, ...], sorted, merged. */
export const EAW_WIDE: readonly number[] = [
${hex(ranges(2))}
]

/** East_Asian_Width A: same layout as EAW_WIDE. */
export const EAW_AMBIGUOUS: readonly number[] = [
${hex(ranges(1))}
]

function inRanges(table: readonly number[], cp: number): boolean {
  let lo = 0
  let hi = table.length / 2 - 1
  while (lo <= hi) {
    const mid = (lo + hi) >> 1
    if (cp < table[mid * 2]!) hi = mid - 1
    else if (cp > table[mid * 2 + 1]!) lo = mid + 1
    else return true
  }
  return false
}

/** 'W' for W or F, 'A' for ambiguous, undefined for every other class. */
export function eawOf(cp: number): 'W' | 'A' | undefined {
  return inRanges(EAW_WIDE, cp) ? 'W' : inRanges(EAW_AMBIGUOUS, cp) ? 'A' : undefined
}
`)
