// Builds the self-contained MCP server: src/entry.mjs + the SDK and zod in one
// ESM file, skills/tmux-agent-tools/scripts/lib/mcp-server.mjs, plus the
// third-party licenses beside it (mcp-server.LICENSES.txt). The core .ts files
// are not bundled; entry.mjs imports them from the bundle's own dir.
//
// Deterministic: fixed options, paths relative to the repo root, no timestamps,
// so test-version-sync-smoke can rebuild and compare bytes.
//
// Usage: node mcp-adapter/build.mjs [--out <dir>]   (default: the skill's scripts/lib)
import { readFileSync, readdirSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const adapterDir = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(adapterDir, "..");
const outIdx = process.argv.indexOf("--out");
const outDir = outIdx > 0 ? resolve(process.argv[outIdx + 1]) : join(repoRoot, "skills/tmux-agent-tools/scripts/lib");
const version = JSON.parse(readFileSync(join(repoRoot, ".claude-plugin/plugin.json"), "utf8")).version;

const result = await build({
  absWorkingDir: repoRoot,
  entryPoints: ["mcp-adapter/src/entry.mjs"],
  bundle: true,
  format: "esm",
  platform: "node",
  target: "node22.18",
  write: false,
  outfile: join(outDir, "mcp-server.mjs"),
  metafile: true,
  sourcemap: false,
  legalComments: "eof",
  logLevel: "warning",
  define: { __TMUX_AGENT_VERSION__: JSON.stringify(version) },
  banner: {
    js: [
      `// tmux-agent-mcp v${version}. Generated by mcp-adapter/build.mjs; do not edit.`,
      "// Third-party licenses: mcp-server.LICENSES.txt beside this file.",
      // Bundled CommonJS calls require() for node builtins; ESM has none.
      'import { createRequire as __tmuxAgentCreateRequire } from "node:module";',
      "const require = __tmuxAgentCreateRequire(import.meta.url);",
    ].join("\n"),
  },
});

// One entry per bundled npm package: name, version, license field, license text.
const packages = new Map();
for (const input of Object.keys(result.metafile.inputs)) {
  const m = input.match(/^(.*node_modules\/(?:@[^/]+\/)?[^/]+)\//);
  if (!m || packages.has(m[1])) continue;
  const dir = join(repoRoot, m[1]);
  const pkg = JSON.parse(readFileSync(join(dir, "package.json"), "utf8"));
  const licenseFile = readdirSync(dir).filter((f) => /^(licen[sc]e|copying)/i.test(f)).sort()[0];
  const text = licenseFile ? readFileSync(join(dir, licenseFile), "utf8").trim() : `(no license file shipped; package.json license: ${pkg.license})`;
  packages.set(m[1], { id: `${pkg.name}@${pkg.version}`, license: pkg.license, text });
}
const notices = [...packages.values()].sort((a, b) => (a.id < b.id ? -1 : 1));
const licenses = [
  `Third-party software bundled in mcp-server.mjs (tmux-agent-mcp v${version}).`,
  "",
  ...notices.flatMap((p) => [`${"=".repeat(72)}`, `${p.id} (${p.license})`, `${"=".repeat(72)}`, p.text, ""]),
].join("\n");

mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, "mcp-server.mjs"), result.outputFiles[0].contents);
writeFileSync(join(outDir, "mcp-server.LICENSES.txt"), licenses);
console.error(`build: ${join(outDir, "mcp-server.mjs")} (${result.outputFiles[0].contents.length} bytes, ${notices.length} packages)`);
